name: pytest

on: [push, pull_request]

jobs:
  run_pytest:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Create conda environment for Windows
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_dev_windows.yml
          micromamba-version: 'latest'
          cache-environment: true

      - name: Install cedalion
        run: |
           python -m pip install -e . --no-deps --force-reinstall

      - name: Running Tests
        run: |
          python -m pytest --verbose
