name: pytest

on: [push, pull_request]

jobs:
  run_pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}


    steps:
      - uses: actions/checkout@v4

      - name: Create conda environment for Linux and MacOS
        if: startsWith(${{matrix.os}}, 'ubuntu') || startsWith(${{matrix.os}}, 'macos')
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_dev.yml
          micromamba-version: 'latest'
          cache-environment: true

      - name: Create conda environment for windows
        if: startsWith(${{matrix.os}}, 'windows')
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment_dev_windows.yml
          micromamba-version: 'latest'
          cache-environment: true

      - name: Install cedalion
        run: |
           python -m pip install -e . --no-deps --force-reinstall

      - name: Running Tests
        run: |
          python -m pytest --verbose
